"""Mental model CRUD for MemoryDB (insights generated by Reflect)."""

import json
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4


class MentalModelMixin:
    """Mental model row operations (expects self.conn)."""

    def insert_mental_model(
        self,
        bank_id: str,
        topic: str,
        insight: str,
        based_on: list[str] | None = None,
    ) -> str:
        """Insert a new mental model (generated by Reflect). Returns the model ID."""
        assert self.conn is not None

        model_id = str(uuid4())
        now = datetime.now(timezone.utc).isoformat()

        self.conn.execute(
            """INSERT INTO mental_models (id, bank_id, topic, insight, based_on, created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, ?)""",
            (model_id, bank_id, topic, insight, json.dumps(based_on or []), now, now),
        )
        self.conn.commit()
        return model_id

    def get_mental_models(self, bank_id: str, limit: int = 10) -> list[dict[str, Any]]:
        """Get recent mental models for a bank."""
        assert self.conn is not None

        rows = self.conn.execute(
            """SELECT * FROM mental_models
               WHERE bank_id = ?
               ORDER BY updated_at DESC
               LIMIT ?""",
            (bank_id, limit),
        ).fetchall()

        return [
            {
                "id": r["id"],
                "topic": r["topic"],
                "insight": r["insight"],
                "based_on": json.loads(r["based_on"]),
                "created_at": r["created_at"],
                "updated_at": r["updated_at"],
            }
            for r in rows
        ]

    def get_mental_model(self, model_id: str) -> dict[str, Any] | None:
        """Get a single mental model by ID."""
        assert self.conn is not None

        row = self.conn.execute(
            "SELECT * FROM mental_models WHERE id = ?", (model_id,)
        ).fetchone()

        if not row:
            return None

        return {
            "id": row["id"],
            "bank_id": row["bank_id"],
            "topic": row["topic"],
            "insight": row["insight"],
            "based_on": json.loads(row["based_on"]),
            "created_at": row["created_at"],
            "updated_at": row["updated_at"],
            "auto_refresh": bool(row["auto_refresh"]) if row["auto_refresh"] is not None else False,
            "source_query": row["source_query"] or "",
        }

    def delete_mental_model(self, model_id: str) -> bool:
        """Delete a mental model. Returns True if found and deleted."""
        assert self.conn is not None

        row = self.conn.execute(
            "SELECT id FROM mental_models WHERE id = ?", (model_id,)
        ).fetchone()
        if not row:
            return False

        self.conn.execute("DELETE FROM mental_models WHERE id = ?", (model_id,))
        self.conn.commit()
        return True

    def update_mental_model(
        self,
        model_id: str,
        topic: str | None = None,
        insight: str | None = None,
        based_on: list[str] | None = None,
    ) -> bool:
        """Update an existing mental model. Returns True if found and updated."""
        assert self.conn is not None

        row = self.conn.execute(
            "SELECT * FROM mental_models WHERE id = ?", (model_id,)
        ).fetchone()
        if not row:
            return False

        new_topic = topic if topic is not None else row["topic"]
        new_insight = insight if insight is not None else row["insight"]
        new_based_on = based_on if based_on is not None else json.loads(row["based_on"])
        now = datetime.now(timezone.utc).isoformat()

        self.conn.execute(
            """UPDATE mental_models
               SET topic = ?, insight = ?, based_on = ?, updated_at = ?
               WHERE id = ?""",
            (new_topic, new_insight, json.dumps(new_based_on), now, model_id),
        )
        self.conn.commit()
        return True

    def insert_mental_model_with_options(
        self,
        bank_id: str,
        topic: str,
        insight: str,
        based_on: list[str] | None = None,
        auto_refresh: bool = False,
        source_query: str = "",
    ) -> str:
        """Insert a mental model with auto_refresh and source_query options."""
        assert self.conn is not None

        model_id = str(uuid4())
        now = datetime.now(timezone.utc).isoformat()

        self.conn.execute(
            """INSERT INTO mental_models
               (id, bank_id, topic, insight, based_on,
                created_at, updated_at, auto_refresh, source_query)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                model_id, bank_id, topic, insight,
                json.dumps(based_on or []), now, now,
                1 if auto_refresh else 0, source_query,
            ),
        )
        self.conn.commit()
        return model_id

    def get_auto_refresh_models(self, bank_id: str) -> list[dict[str, Any]]:
        """Get all mental models with auto_refresh enabled for a bank."""
        assert self.conn is not None

        rows = self.conn.execute(
            """SELECT * FROM mental_models
               WHERE bank_id = ? AND auto_refresh = 1""",
            (bank_id,),
        ).fetchall()

        return [
            {
                "id": r["id"],
                "bank_id": r["bank_id"],
                "topic": r["topic"],
                "insight": r["insight"],
                "based_on": json.loads(r["based_on"]),
                "source_query": r["source_query"] or r["topic"],
                "created_at": r["created_at"],
                "updated_at": r["updated_at"],
            }
            for r in rows
        ]
